import React from "react";
import { IosSymbol } from "./IosSymbol";
import { provenanceCaption, provenanceTone } from "./provenance.mjs";

export type ValidatorStatus = "passed" | "warnings" | "failed";

export type ContentProvenance = {
  generated_by: string;
  prompt_template_version: string;
  grounding_score?: number | null;
  validator_status: ValidatorStatus | string;
  validator_warnings?: string[];
};

type ProviderBadgeProps = {
  provider?: "bedrock" | "gemini" | "";
  provenance?: ContentProvenance | null;
};

const FALLBACK_LABELS: Record<"bedrock" | "gemini", string> = {
  bedrock: "Generated by Claude · AWS Bedrock",
  gemini: "Generated by Gemini",
};

/**
 * AI-provenance caption for LLM-generated reports and explanations.
 * Extends the earlier "Powered by Claude" badge with validator status
 * and optional Guardrails grounding score.
 */
export function ProviderBadge({ provider, provenance }: ProviderBadgeProps): React.ReactElement | null {
  if (provenance) {
    const tone = provenanceTone(provenance.validator_status);
    return (
      <span
        className={`provider-badge provider-badge--${tone}`}
        data-testid="provenance-badge"
        data-validator-status={tone}
        title={`Prompt template ${provenance.prompt_template_version}${
          provenance.validator_warnings?.length ? ` · ${provenance.validator_warnings.join(", ")}` : ""
        }`}
      >
        <IosSymbol name="sparkle" size={12} strokeWidth={1.6} />
        {provenanceCaption(provenance)}
      </span>
    );
  }
  if (!provider) return null;
  return (
    <span className="provider-badge" title="AI-generated content — model provenance">
      <IosSymbol name="sparkle" size={12} strokeWidth={1.6} />
      {FALLBACK_LABELS[provider]}
    </span>
  );
}
